### ISSUE TITLE
Form Tiếp nhận trẻ

### ISSUE THREAD

**Issue by vthhanh96** [vanhongha/QLNT_OODA#1]
- [x] Kiểm tra tính hợp lệ khi tiếp nhận trẻ, ví dụ không được để trống tên trẻ khi tiếp nhận

- [x] Nút Xếp lớp ngay không biết khi nào được enable nhỉ?

- [x] Nên thêm một button Đóng có chức năng close tab

- [x] Hiện tại khi thêm một trẻ không có tên thì khi click lại trẻ đó bị lỗi như hình 
![image](https://user-images.githubusercontent.com/19782537/33841292-ee186bb0-dec9-11e7-86d2-583949958037.png)

- [x] Khi xóa 1 trẻ vừa mới thêm bị lỗi như hình
![image](https://user-images.githubusercontent.com/19782537/33841484-6fa52830-deca-11e7-8e5e-a1448943c577.png)

- [x] Please remove messagebox này khi click button Lưu chỉnh sửa
![image](https://user-images.githubusercontent.com/19782537/33841550-a7c86f10-deca-11e7-86a0-a7379f97a013.png)

**Comment by phamnutuyetan** [comment]
Nút xếp lớp và nút close tab nói con Hà nha, t kêu nó lâu rồi 
Còn vụ Delete là database Lệ thêm vô bị conflict
