### ISSUE TITLE
Lỗi trong thực đơn

### ISSUE THREAD

**Issue by phamnutuyetan** [vanhongha/QLNT_OODA#15]
- [x] Trong các bảng, ô nào không cho chỉnh sửa thì nên để ReadOnly=true, nếu không người dùng chỉnh sửa nhưng lại không thấy có tác động gì 

- [x] Nút Báo cáo nhà bếp và xuất danh sách trong lịch ăn không thấy thông báo gì khi bấm?

- [x] Bảng có món ăn nhưng báo món ăn không tồn tại khi bấm xóa
![image](https://user-images.githubusercontent.com/22116782/33934706-45dfd5f0-e02c-11e7-8281-535f59979f09.png)

**Comment by vyle3696** [comment]
cái bấm xóa mà nó báo không có món ăn trong bảng vì nút xóa đó là xóa món ăn theo combobox, món ăn trong bảng là món thịt xào, món chọn để xóa lại là gà hầm nên nó báo lỗi không có

**Comment by phamnutuyetan** [comment]
vậy dễ hiểu lầm quá vậy, có cách nào cho nó trực quan hơn không, thường người ta sẽ nghĩ xóa là xóa dòng được chọn trong bảng
