### ISSUE TITLE
Form Xếp lớp

### ISSUE THREAD

**Issue by vthhanh96** [vanhongha/QLNT_OODA#2]
- [x]  Khi chọn chế độ chuyển lớp thì ko hiện những học sinh chưa có lớp lên datagridview
![image](https://user-images.githubusercontent.com/19782537/33842015-ea582842-decb-11e7-80ec-e31562b764b1.png)

- [x] Lỗi khi bấm thôi học 
![image](https://user-images.githubusercontent.com/19782537/33842146-46b25072-decc-11e7-91ba-139ebcc7ea95.png)

- [x] Nếu click chọn chuyển tất cả trẻ của một lớp sang một lớp mới mà trong đó có trẻ đã thôi học thì chuyển những trẻ bình thường qua chứ ko báo lỗi rồi ko chuyển nữa
![image](https://user-images.githubusercontent.com/19782537/33842328-d06c7f54-decc-11e7-8406-7cb7c8a6da4f.png)

- [x] Sau khi xảy ra trường hợp trên thì click chuyển một trẻ lại qua hết tất cả trẻ như hình
![image](https://user-images.githubusercontent.com/19782537/33842455-2b5d4a56-decd-11e7-93a2-ffa5eaf96c3d.png)

- [x] Nếu chọn hai bên lớp giống nhau thì ko có gì xảy ra khi click các button chuyển trẻ
![image](https://user-images.githubusercontent.com/19782537/33842538-62b170f4-decd-11e7-8f1b-c299839c66ad.png)

- [x] Nút Đóng không có tác dụng

- [x] Khi click thôi học nên có một message box confirm

**Comment by vanhongha** [comment]
Con Hạnh chưa test lại mà @@
